log_path: logs/app.log
is_prod: true
server_address: localhost:50051
base_url: https://api.namecheap.com/xml.response?ApiUser=user&ApiKey=key&UserName=username&ClientIp=ip&SLD=domain&TLD=com&Command=
